# Generated by Django 3.1.5 on 2021-01-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sarthi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1080)),
                ('contact', models.CharField(max_length=1080)),
                ('Address', models.CharField(max_length=1080)),
                ('vehicleNo', models.CharField(max_length=1080)),
                ('ClassId', models.CharField(max_length=1080)),
                ('InsuranceNo', models.CharField(max_length=1080)),
                ('InsuranceStartDate', models.CharField(max_length=1080)),
                ('InsuranceExpiryDate', models.CharField(max_length=1080)),
                ('PUCNo', models.CharField(max_length=1080)),
                ('PUCStartDate', models.CharField(max_length=1080)),
                ('PUCExpiryDate', models.CharField(max_length=1080)),
                ('FitnessNo', models.CharField(max_length=1080)),
                ('FitnessStartDate', models.CharField(max_length=1080)),
                ('FitnessExpiryDate', models.CharField(max_length=1080)),
                ('PermitNo', models.CharField(max_length=1080)),
                ('PermitStartDate', models.CharField(max_length=1080)),
                ('PermitExpiryDate', models.CharField(max_length=1080)),
                ('TaxNo', models.CharField(max_length=1080)),
                ('TaxStartDate', models.CharField(max_length=1080)),
                ('TaxExpiryDate', models.CharField(max_length=1080)),
                ('GTNo', models.CharField(max_length=1080)),
                ('GTStartDate', models.CharField(max_length=1080)),
                ('GTExpiryDate', models.CharField(max_length=1080)),
                ('PTNo', models.CharField(max_length=1080)),
                ('PTStartDate', models.CharField(max_length=1080)),
                ('PTExpiryDate', models.CharField(max_length=1080)),
                ('services', models.CharField(max_length=1000)),
                ('Expiry', models.DateField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=120)),
                ('Paid', models.DecimalField(decimal_places=3, max_digits=120)),
                ('Remaining', models.DecimalField(decimal_places=3, max_digits=120)),
                ('systemDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SarthiClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.CharField(max_length=1080)),
                ('title', models.CharField(max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SarthiServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.CharField(max_length=1080)),
                ('title', models.CharField(max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SarthiServiesTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SarthiId', models.CharField(max_length=1080)),
                ('ServiceName', models.CharField(blank=True, max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vahaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1080)),
                ('contact', models.CharField(max_length=1080)),
                ('DOB', models.CharField(max_length=1080)),
                ('Class', models.CharField(max_length=1080)),
                ('Address', models.CharField(max_length=1080)),
                ('ApplicationNo', models.CharField(max_length=1080)),
                ('EnrollmentNo', models.CharField(max_length=1080)),
                ('LearningNo', models.CharField(max_length=1080)),
                ('LicenseNo', models.CharField(max_length=1080)),
                ('services', models.CharField(max_length=1000)),
                ('Expiry', models.DateField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=120)),
                ('Paid', models.DecimalField(decimal_places=3, max_digits=120)),
                ('Remaining', models.DecimalField(decimal_places=3, max_digits=120)),
                ('systemDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VahaanClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.CharField(max_length=1080)),
                ('title', models.CharField(max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VahaanServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.CharField(max_length=1080)),
                ('title', models.CharField(max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VahaanServiesTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VahaanId', models.CharField(max_length=1080)),
                ('ServiceName', models.CharField(blank=True, max_length=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
